---
title: "R Notebook"
output: html_notebook
---

```{r}
p <- c(0.01, 0.05, 0.10, 0.25, 0.50)
R <- 2^(2:15)
phat<- matrix(NA,length(R),length(p))
for(i in 1: length(p)){
  for (j in 1:length(R)){
    phat[j,i]<-rbinom(1,R[j],p[i])/R[j]
    
  }
}

abs_error <- matrix(NA, length(R), length(p))

for (i in 1: length(R)) {
  abs_error[i,] <- abs(p-phat[i,])
}


rel_error <- matrix(NA, length(R), length(p))

for (i in 1: length(R)) {
  rel_error[i,] <- (abs_error[i,]/p)
}




plot(R,seq(0,.15,length.out= length(R)),type="n")
lines(R, abs_error[,1], col="red")

view(abs_error)     

```

```{r}
```{r}
p <- c(0.01, 0.05, 0.10, 0.25, 0.50)
R <- 2^(2:15)

abs_error <- matrix(NA,length(R),length(p))
for(i in 1: length(p)){
  for (j in 1:length(R)){
    phat[j,i]<-onecal(R[j], p[i])
    
  }
}

abs_error <- matrix(NA, length(R), length(p))

for (i in 1: length(R)) {
  abs_error[i,] <- abs(p-phat[i,])
}


rel_error <- matrix(NA, length(R), length(p))

for (i in 1: length(R)) {
  rel_error[i,] <- (abs_error[i,]/p)
}




plot(R,seq(0,.15,length.out= length(R)),type="n")
lines(R, abs_error[,1], col="red")

view(abs_error)
```

